# Generated by Django 3.2.5 on 2022-04-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0003_auto_20220405_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adboard',
            old_name='mainpotho',
            new_name='mainphoto',
        ),
    ]
