# Generated by Django 3.2.5 on 2022-04-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0004_rename_mainpotho_adboard_mainphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='adboard',
            name='link',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
