# Generated by Django 3.2.5 on 2022-04-12 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_api_id', models.IntegerField(verbose_name='축제api_id')),
                ('view_cnt', models.PositiveIntegerField(default=0, verbose_name='검색수')),
            ],
            options={
                'verbose_name': '축제컨텐츠',
                'verbose_name_plural': '축제컨텐츠(들)',
                'db_table': 'festival',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_api_id', models.IntegerField(verbose_name='숙소api_id')),
                ('view_cnt', models.PositiveIntegerField(default=0, verbose_name='검색수')),
            ],
            options={
                'verbose_name': '숙소컨텐츠',
                'verbose_name_plural': '숙소컨텐츠(들)',
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_api_id', models.IntegerField(verbose_name='식당api_id')),
                ('view_cnt', models.PositiveIntegerField(default=0, verbose_name='검색수')),
            ],
            options={
                'verbose_name': '식당컨텐츠',
                'verbose_name_plural': '식당컨텐츠(들)',
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_api_id', models.IntegerField(verbose_name='여행api_id')),
                ('view_cnt', models.PositiveIntegerField(default=0, verbose_name='검색수')),
            ],
            options={
                'verbose_name': '여행컨텐츠',
                'verbose_name_plural': '여행컨텐츠(들)',
                'db_table': 'travel',
            },
        ),
        migrations.CreateModel(
            name='T_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_tag', models.CharField(max_length=32, verbose_name='태그')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.hotel', verbose_name='여행id')),
            ],
            options={
                'verbose_name': '여행태그',
                'verbose_name_plural': '여행태그(들)',
                'db_table': 't_tag',
            },
        ),
        migrations.CreateModel(
            name='T_bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.travel', verbose_name='여행id')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='검색사용자')),
            ],
            options={
                'verbose_name': '여행북마크',
                'verbose_name_plural': '여행북마크(들)',
                'db_table': 't_bookmark',
            },
        ),
        migrations.CreateModel(
            name='R_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_tag', models.CharField(max_length=32, verbose_name='태그')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.restaurant', verbose_name='식당id')),
            ],
            options={
                'verbose_name': '식당태그',
                'verbose_name_plural': '식당태그(들)',
                'db_table': 'r_tag',
            },
        ),
        migrations.CreateModel(
            name='R_bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.restaurant', verbose_name='식당id')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='검색사용자')),
            ],
            options={
                'verbose_name': '식당북마크',
                'verbose_name_plural': '식당북마크(들)',
                'db_table': 'r_bookmark',
            },
        ),
        migrations.CreateModel(
            name='H_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_tag', models.CharField(max_length=32, verbose_name='태그')),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.hotel', verbose_name='숙소id')),
            ],
            options={
                'verbose_name': '숙소태그',
                'verbose_name_plural': '숙소태그(들)',
                'db_table': 'h_tag',
            },
        ),
        migrations.CreateModel(
            name='H_bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.hotel', verbose_name='숙소id')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='검색사용자')),
            ],
            options={
                'verbose_name': '숙소북마크',
                'verbose_name_plural': '숙소북마크(들)',
                'db_table': 'h_bookmark',
            },
        ),
        migrations.CreateModel(
            name='F_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_tag', models.CharField(max_length=32, verbose_name='태그')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.hotel', verbose_name='축제id')),
            ],
            options={
                'verbose_name': '축제태그',
                'verbose_name_plural': '축제태그(들)',
                'db_table': 'f_tag',
            },
        ),
        migrations.CreateModel(
            name='F_bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.festival', verbose_name='축제id')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='검색사용자')),
            ],
            options={
                'verbose_name': '축제북마크',
                'verbose_name_plural': '축제북마크(들)',
                'db_table': 'f_bookmark',
            },
        ),
    ]
