# Generated by Django 3.2.5 on 2022-04-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='mapx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='mapy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
