# Generated by Django 3.2.5 on 2022-04-05 04:15

from django.db import migrations, models
import member.validators


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20220404_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=256, null=True, validators=[member.validators.validate_no_special_characters], verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, null=True, validators=[member.validators.validate_no_special_characters], verbose_name='성명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임입니다.'}, max_length=32, null=True, unique=True, validators=[member.validators.validate_no_special_characters], verbose_name='닉네임'),
        ),
    ]
