# Generated by Django 3.2.5 on 2022-04-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20220405_1315'),
        ('member', '0003_auto_20220405_1429'),
    ]

    operations = [
    ]
