# Generated by Django 3.2.5 on 2022-04-10 19:56

from django.db import migrations, models
import member.validators


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_merge_0003_auto_20220405_1315_0003_auto_20220405_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=4, null=True, validators=[member.validators.validate_age], verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=2, null=True, validators=[member.validators.validate_gender], verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(error_messages={'unique': '이미 사용중인 핸드폰번호입니다.'}, max_length=16, null=True, unique=True, validators=[member.validators.validate_mobile], verbose_name='폰번호'),
        ),
    ]
