# Generated by Django 3.2.5 on 2022-04-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20220411_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_social_login',
            field=models.CharField(default='', max_length=16, null=True, verbose_name='소셜로그인여부'),
        ),
    ]
