# Generated by Django 3.2.5 on 2022-04-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20220411_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='밴 끝나는 날짜'),
        ),
    ]
