# Generated by Django 3.2.5 on 2022-04-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_user_ban_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ban_end_date',
        ),
    ]
