# Generated by Django 3.2.5 on 2022-04-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20220405_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventboard',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='EventFiles/'),
        ),
    ]
