# Generated by Django 3.2.5 on 2022-04-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventboard_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventboard',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='eventboard',
            name='mainpotho',
            field=models.FileField(blank=True, null=True, upload_to='EventFiles/'),
        ),
    ]
