# Generated by Django 3.2.5 on 2022-04-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_comment', models.TextField(verbose_name='후기댓글')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='댓글등록시간')),
            ],
        ),
        migrations.CreateModel(
            name='F_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='축제후기제목')),
                ('content', models.TextField(verbose_name='축제후기내용')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='축제평점')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='축제썸네일')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='축제후기등록시간')),
                ('up_date', models.DateTimeField(auto_now_add=True, verbose_name='축제후기최신화시간')),
            ],
            options={
                'verbose_name': '축제후기',
                'verbose_name_plural': '축제후기(들)',
                'db_table': 'f_review',
            },
        ),
        migrations.CreateModel(
            name='H_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_comment', models.TextField(verbose_name='후기댓글')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='댓글등록시간')),
            ],
        ),
        migrations.CreateModel(
            name='H_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='숙소후기제목')),
                ('content', models.TextField(verbose_name='숙소후기내용')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='숙소평점')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='숙소썸네일')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='숙소후기등록시간')),
                ('up_date', models.DateTimeField(auto_now_add=True, verbose_name='숙소후기최신화시간')),
            ],
            options={
                'verbose_name': '숙소후기',
                'verbose_name_plural': '숙소후기(들)',
                'db_table': 'h_review',
            },
        ),
        migrations.CreateModel(
            name='R_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_comment', models.TextField(verbose_name='후기댓글')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='댓글등록시간')),
            ],
        ),
        migrations.CreateModel(
            name='R_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='식당후기제목')),
                ('content', models.TextField(verbose_name='식당후기내용')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='식당평점')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='식당썸네일')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='식당후기등록시간')),
                ('up_date', models.DateTimeField(auto_now_add=True, verbose_name='식당후기최신화시간')),
            ],
            options={
                'verbose_name': '식당후기',
                'verbose_name_plural': '식당후기(들)',
                'db_table': 'r_review',
            },
        ),
        migrations.CreateModel(
            name='T_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_comment', models.TextField(verbose_name='후기댓글')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='댓글등록시간')),
            ],
        ),
        migrations.CreateModel(
            name='T_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='여행후기제목')),
                ('content', models.TextField(verbose_name='여행후기내용')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='여행평점')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='여행썸네일')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='여행후기등록시간')),
                ('up_date', models.DateTimeField(auto_now_add=True, verbose_name='여행후기최신화시간')),
            ],
            options={
                'verbose_name': '여행후기',
                'verbose_name_plural': '여행후기(들)',
                'db_table': 't_review',
            },
        ),
        migrations.CreateModel(
            name='T_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_reply', models.TextField(verbose_name='후기대댓글')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='대댓글등록시간')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.t_comment', verbose_name='대상댓글')),
            ],
        ),
        migrations.AddField(
            model_name='t_comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.t_review', verbose_name='후기댓글'),
        ),
        migrations.CreateModel(
            name='R_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_reply', models.TextField(verbose_name='후기대댓글')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='대댓글등록시간')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.r_comment', verbose_name='대상댓글')),
            ],
        ),
        migrations.AddField(
            model_name='r_comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.r_review', verbose_name='후기댓글'),
        ),
        migrations.CreateModel(
            name='H_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_reply', models.TextField(verbose_name='후기대댓글')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='대댓글등록시간')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.h_comment', verbose_name='대상댓글')),
            ],
        ),
        migrations.AddField(
            model_name='h_comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.h_review', verbose_name='후기댓글'),
        ),
        migrations.CreateModel(
            name='F_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_reply', models.TextField(verbose_name='후기대댓글')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='대댓글등록시간')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.f_comment', verbose_name='대상댓글')),
            ],
        ),
        migrations.AddField(
            model_name='f_comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.f_review', verbose_name='후기댓글'),
        ),
    ]
