# Generated by Django 3.2.5 on 2022-04-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(auto_now_add=True, unique=True)),
                ('login_cnt', models.IntegerField(default=0)),
                ('join_cnt', models.IntegerField(default=0)),
                ('board_cnt', models.IntegerField(default=0)),
                ('board_view_cnt', models.IntegerField(default=0)),
                ('comment_cnt', models.IntegerField(default=0)),
                ('trip_view_cnt', models.IntegerField(default=0)),
                ('food_view_cnt', models.IntegerField(default=0)),
                ('lodging_view_cnt', models.IntegerField(default=0)),
                ('festival_view_cnt', models.IntegerField(default=0)),
                ('review_cnt', models.IntegerField(default=0)),
                ('review_view_cnt', models.IntegerField(default=0)),
                ('event_view_cnt', models.IntegerField(default=0)),
                ('ad_view_cnt', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'count_board',
            },
        ),
    ]
