# Generated by Django 3.2.5 on 2022-04-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AddField(
            model_name='board',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to='UploadedFiles/', verbose_name='파일'),
        ),
    ]
