# Generated by Django 3.2.5 on 2022-04-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_comment_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요 수'),
        ),
    ]
