# Generated by Django 3.2.5 on 2022-04-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_board_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='닉네임'),
        ),
    ]
