# Generated by Django 3.2.5 on 2022-04-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_comment_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_hits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_user', models.CharField(max_length=20, null=True, verbose_name='접속 ID')),
                ('connect_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='접속 Board')),
            ],
            options={
                'db_table': 'board_hits',
            },
        ),
    ]
