# Generated by Django 3.2.5 on 2022-04-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_board_hits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board_hits',
        ),
    ]
